### ISSUE TITLE
Ref/Liquid [R134a/POE32] not implemented: CompressorTest.py

### ISSUE THREAD

**Issue by Jeffersonjjsk** [CenterHighPerformanceBuildingsPurdue/ACHP#35]
When running the _ACHP-master>ComponentTests>CompressorTest.py_, the result indicates 'Ref/Liquid [R134a/POE32] not implemented'

Even when I replace R134a with R410a, the result still shows 'Ref/Liquid [R410a/POE32] not implemented'. Even when I change the Backend to the other refrigeration library, the results are still the same.

**Comment by abahman** [comment]
The solubility calculation is used for the charge calculation (amount of refrigerant dissolve in oil) which is based on the library available in OilPropLib.py.
For now only POE32 and R407C mixture is available in the library. However, you can update this library for R134a or R410A with POE32 if you found the solubility data in the literature. 
As a courtesy from you, upon updating the library, you can pull request the changes.
Thank you
