### ISSUE TITLE
PHECycle.py: 

### ISSUE THREAD

**Issue by Jeffersonjjsk** [CenterHighPerformanceBuildingsPurdue/ACHP#36]
File: "ACHP-master> Cycle Tests> PHECycle.py"
After running the file, the result shows: 'ValueError: math domain error'. What do we do to fix it?

**Comment by abahman** [comment]
Thank you for citing this out. This example was generated for experimental purposes and it is not a general example. It needs more debugging.
If you want to exercise the secondary loop cycle, I suggest you work with SLACTest.py
