### ISSUE TITLE
File: "ACHP-master> Cycle Tests> SampleCycles.py"

### ISSUE THREAD

**Issue by Jeffersonjjsk** [CenterHighPerformanceBuildingsPurdue/ACHP#37]
File: "ACHP-master> Cycle Tests> SampleCycles.py"

Here are some errors I met in this file.
          -->AttributeError: DXCycleClass instance has no attribute 'Backend' --> this can be solved by adding Cycle.Backend='HEOS' into line 430(The DXCycleClass part)
                -->AssertionError: Unmatched fields found:['Ref'] -->  Refrigerant is R410a. How we resolve this problem?
I tried to run the SampleSecondaryLoopSystem separately and it works fine after putting into HEOS library(see [test code](https://drive.google.com/file/d/1Of3q0PhXcZAJcHpCGMDH-zO_3GEDv1gT/view?usp=sharing)). However, I cannot make the SampleCycles.py to work. Any suggestion on how to fix the code?

**Comment by abahman** [comment]
Thank you for mentioning this.
This can be resolved by removing ('Ref':     Cycle.Ref) from the lines (95,302,494,and 679).
